permalink:           pretty
relative_permalinks: true

# Setup
title:               Roy Inganta Ginting
tagline:             'Berbagi Pengetahuan'
description:         ''
url:                 https://ringanta.github.io
paginate:            5
highlighter:         pygments

# About/contact
author:
  name:              Roy Inganta Ginting
  url:               https://twitter.com/ringanta
  email:             ringanta.ginting@gmail.com

gems:
  - jekyll-sitemap
