permalink:           pretty
relative_permalinks: true

# Setup
title:               Roy Inganta Ginting
tagline:             'Berbagi Pengetahuan'
description:         ''
url:                 https://ringanta.github.io
baseurl:             ''
paginate:            5
pygments:            true

# About/contact
author:
  name:              Roy Inganta Ginting
  url:               https://twitter.com/ringanta
  email:             ringanta.ginting@gmail.com

